[phases.setup]
commands = [
  "echo Setting up environment..."
]

[phases.install]
commands = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
commands = [
  "cd frontend && npm run build",
  "cd backend && npm run build"
]

[phases.start]
commands = [
  "cd backend && npm run start"
]

[env]
NODE_VERSION = "18"
